<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<LangVersion>13.0</LangVersion>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<AssemblyName>Icod.Processes.ProcessTestHost</AssemblyName>
		<RootNamespace>Icod.Processes.ProcessTestHost</RootNamespace>
		<Configurations>Debug;Release;Staging</Configurations>
		<DebugType>portable</DebugType>
		<DebugSymbols>true</DebugSymbols>
		<SignAssembly>false</SignAssembly>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
		<WarningLevel>2</WarningLevel>
		<Optimize>false</Optimize>
		<DefineConstants>DEBUG;TRACE</DefineConstants>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)' == 'Staging' ">
		<WarningLevel>3</WarningLevel>
		<Optimize>false</Optimize>
		<DefineConstants>TRACE</DefineConstants>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
		<WarningLevel>4</WarningLevel>
		<Optimize>true</Optimize>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<WarningsNotAsErrors>CS1591</WarningsNotAsErrors>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\Icod.Processes.csproj" />
	</ItemGroup>
</Project>
